# Site settings
title: Recipes
email: your-email@domain.com
description: The plain text recipe database for hackers
baseurl: ""
twitter_username: clarklab
github_username:  aneisch

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '_recipes/aaa-template.md', 'readme.md', 'LICENSE']
